name: Deploy to GitHub Pages (No Cache)

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Clear yarn cache
      working-directory: ./frontend
      run: yarn cache clean

    - name: Install dependencies (no cache)
      working-directory: ./frontend
      run: yarn install --no-cache

    - name: Build the app
      working-directory: ./frontend
      run: yarn build

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Deploy to GitHub Pages
      working-directory: ./frontend
      run: |
        npx gh-pages -d build -u "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"