# This workflow is disabled - using deploy-no-cache.yml instead
name: Deploy to GitHub Pages (Manual DISABLED)

# Commented out to disable this workflow
# on:
#   push:
#     branches: [ main, master ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock

    - name: Install dependencies
      working-directory: ./frontend
      run: yarn install

    - name: Build the app
      working-directory: ./frontend
      run: yarn build

    - name: Configure git
      run: |
        git config --global user.name 'hammoudi'
        git config --global user.email 'hammoudi.pro6@gmail.com'

    - name: Deploy to GitHub Pages
      working-directory: ./frontend
      run: |
        npx gh-pages -d build -u "hammoudi hammoudi.pro6@gmail.com"
